services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8008
    # command: gunicorn cf.wsgi:application --bind 0.0.0.0:8008
    volumes:
      - ./app/:/usr/src/app/
    #   - static_volume:/home/app/web/staticfiles
    #   - media_volume:/home/app/web/mediafiles

    env_file:
      - ./.env
    ports:
      - 8008:8008
    # expose:
    #   - 8000
    # depends_on:
    #   - db
  # db:
  #   image: postgres:17rc1-bookworm
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   env_file:
  #     - ./.env

  # nginx:
  #   build: ./nginx
  #   volumes:
  #     - static_volume:/home/app/web/staticfiles
  #     - media_volume:/home/app/web/mediafiles
  #   ports:
  #     - 1337:80
  #   depends_on:
  #     - web

# volumes:
#   postgres_data:
#   static_volume:
#   media_volume: