# Generated by Django 5.1.1 on 2024-10-01 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ONE', 'One'), ('TWO', 'two'), ('N/A', 'n/a'), ('OTHER', 'other')], default='N/A', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ONE', 'One'), ('TWO', 'two'), ('N/A', 'n/a'), ('OTHER', 'other')], default='N/A', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='vLan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subnet', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('rack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='networks.rack')),
                ('stack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='networks.stack')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('port', models.PositiveIntegerField(null=True)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('stack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networks.stack')),
                ('switch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='networks.switch')),
                ('vlan', models.ManyToManyField(blank=True, to='networks.vlan')),
            ],
            options={
                'ordering': ['port'],
                'unique_together': {('switch', 'port')},
            },
        ),
    ]
