# Generated by Django 5.1.1 on 2024-09-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='location',
        ),
        migrations.AlterField(
            model_name='network',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='port',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
