# Generated by Django 5.1.1 on 2024-10-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stack',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
