# Generated by Django 5.1.1 on 2024-09-24 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0002_remove_rack_location_alter_network_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='network',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='networks.network'),
        ),
        migrations.AlterField(
            model_name='port',
            name='vlan',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
