# Generated by Django 5.1.1 on 2024-10-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0002_alter_rack_name_alter_stack_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='switch',
            options={'verbose_name_plural': 'switches'},
        ),
        migrations.AlterField(
            model_name='port',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
