# Generated by Django 5.1.1 on 2024-10-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0003_alter_switch_options_alter_port_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
