# Generated by Django 5.1.1 on 2024-09-24 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0004_alter_port_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='stack',
        ),
        migrations.AddField(
            model_name='stack',
            name='switch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='networks.switch'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='rack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='networks.rack'),
        ),
    ]
