# Generated by Django 5.1.1 on 2024-10-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0004_alter_port_slug_alter_switch_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
