# Generated by Django 5.1.1 on 2024-09-24 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0005_remove_switch_stack_stack_switch_alter_switch_rack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='switch',
        ),
        migrations.AddField(
            model_name='switch',
            name='stack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='networks.stack'),
        ),
    ]
