# Generated by Django 5.1.1 on 2024-10-02 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0006_alter_switch_rack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vlan',
            options={'verbose_name': 'vlan', 'verbose_name_plural': 'vlans'},
        ),
        migrations.RenameField(
            model_name='vlan',
            old_name='subnet',
            new_name='role',
        ),
    ]
