# Generated by Django 5.1.1 on 2024-09-24 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0006_remove_stack_switch_switch_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='stack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='networks.stack'),
        ),
        migrations.AlterField(
            model_name='port',
            name='status',
            field=models.CharField(choices=[('v', 'voice'), ('d', 'data'), ('v-d', 'voice-data'), ('dw', 'down')], max_length=10),
        ),
    ]
