# Generated by Django 5.1.1 on 2024-10-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0007_alter_vlan_options_rename_subnet_vlan_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='vlan',
            field=models.ManyToManyField(blank=True, related_name='vlans', to='networks.vlan'),
        ),
    ]
