# Generated by Django 5.1.1 on 2024-10-02 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0008_alter_port_vlan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='stack',
        ),
    ]
