# Generated by Django 5.1.1 on 2024-09-24 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0008_alter_port_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='stack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networks.stack'),
        ),
        migrations.AlterField(
            model_name='port',
            name='switch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networks.switch'),
        ),
    ]
