# Generated by Django 5.1.1 on 2024-10-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0009_remove_port_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
