# Generated by Django 5.1.1 on 2024-09-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0009_alter_port_stack_alter_port_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='status',
            field=models.CharField(choices=[('v', 'voice'), ('d', 'data'), ('v-d', 'voice-data'), ('dw', 'down'), ('u', 'uplink')], max_length=10),
        ),
    ]
