# Generated by Django 5.1.1 on 2024-09-25 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0012_alter_port_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='stack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='networks.stack'),
        ),
    ]
