# Generated by Django 5.1.1 on 2024-10-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0012_rack_colour_stack_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
    ]
