# Generated by Django 5.1.1 on 2024-09-25 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0013_alter_switch_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='rack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='networks.rack'),
        ),
    ]
