# Generated by Django 5.1.1 on 2024-09-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0014_alter_switch_rack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='status',
            field=models.CharField(choices=[('v', 'voice'), ('d', 'data'), ('v-d', 'voice-data'), ('dw', 'down'), ('u', 'uplink')], default='v-d', max_length=10),
        ),
    ]
