# Generated by Django 5.1.1 on 2024-10-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0014_stack_switch_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='switch_number',
        ),
        migrations.AddField(
            model_name='switch',
            name='switch_stack_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
