# Generated by Django 5.1.1 on 2024-09-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0015_alter_port_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='port',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], max_length=2, null=True),
        ),
    ]
