# Generated by Django 5.1.1 on 2024-10-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0015_remove_stack_switch_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switch',
            old_name='switch_stack_number',
            new_name='number_in_stack',
        ),
    ]
