# Generated by Django 5.1.1 on 2024-09-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0017_alter_port_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='name',
        ),
    ]
