# Generated by Django 5.1.1 on 2024-09-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0018_remove_port_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='port',
            options={'ordering': ['port']},
        ),
        migrations.AlterField(
            model_name='port',
            name='status',
            field=models.CharField(choices=[('voice', 'voice'), ('data', 'data'), ('voice-data', 'voice-data'), ('down', 'down'), ('uplink', 'uplink'), ('DMZ', 'DMZ'), ('MGMT', 'MGMT'), ('WIFI', 'WIFI'), ('projects', 'projects')], default='v-d', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='port',
            unique_together={('switch', 'port')},
        ),
    ]
